version: "3.8"

services:
  postgres:
    container_name: api-short-url-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api-short-url
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres

  redis:
    container_name: api-short-url-redis
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=docker
    volumes:
      - ./data/redis:/data
